// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanHosts() {
  return window['go']['main']['App']['CleanHosts']();
}

export function DomReady() {
  return window['go']['main']['App']['DomReady']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLog() {
  return window['go']['main']['App']['GetLog']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Reprobe() {
  return window['go']['main']['App']['Reprobe']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleSite(arg1, arg2) {
  return window['go']['main']['App']['ToggleSite'](arg1, arg2);
}
