// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {logger} from '../models';
import {intercept} from '../models';
import {context} from '../models';

export function CleanHosts():Promise<void>;

export function DomReady():Promise<void>;

export function GetAutoStart():Promise<boolean>;

export function GetConfig():Promise<config.AppConfig>;

export function GetLog():Promise<Array<logger.LogEntry>>;

export function GetStatus():Promise<intercept.Status>;

export function HideToTray():Promise<void>;

export function Minimize():Promise<void>;

export function Quit():Promise<void>;

export function Reprobe():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function Start():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;

export function ToggleSite(arg1:string,arg2:boolean):Promise<void>;
